project_id = "uyeuoexdbivbgqwsmewd"

[functions.download-proxy]
verify_jwt = false

[functions.pesapal-pay]
verify_jwt = false

[functions.pesapal-ipn]
verify_jwt = false

[functions.pesapal-status]
verify_jwt = false
